In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
texts = [
    'There is Horse',
    'I am a Student',
    'I am curious for Software Development',
    'I love to read Data Science related articles',
    'I have a laptop'
]

In [7]:
voc_size = 10000

In [10]:
one_hot_rep = [one_hot(words, voc_size) for words in texts]
one_hot_rep

[[1805, 5986, 7683],
 [1234, 5934, 6551, 7154],
 [1234, 5934, 5967, 2082, 7830, 7589],
 [1234, 9319, 7090, 8545, 1350, 4613, 3225, 8390],
 [1234, 5946, 6551, 4589]]

In [11]:
max_length = 10

In [13]:
## embedding the layer
embedded_words = pad_sequences(sequences=one_hot_rep, maxlen=max_length, padding='post')
embedded_words

array([[1805, 5986, 7683,    0,    0,    0,    0,    0,    0,    0],
       [1234, 5934, 6551, 7154,    0,    0,    0,    0,    0,    0],
       [1234, 5934, 5967, 2082, 7830, 7589,    0,    0,    0,    0],
       [1234, 9319, 7090, 8545, 1350, 4613, 3225, 8390,    0,    0],
       [1234, 5946, 6551, 4589,    0,    0,    0,    0,    0,    0]])

In [16]:
dim = 20
model = Sequential()
embedding_layer = Embedding(input_dim=voc_size, output_dim=dim)
model.add(embedding_layer)
embedding_layer.build((None, max_length))

In [17]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ (None, 10, 20)              │         200,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 200,000 (781.25 KB)

 Trainable params: 200,000 (781.25 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_words)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[[ 0.02378196, -0.03409757, -0.01339421, -0.04283425,
          0.01970315,  0.00146086, -0.03177111, -0.00470096,
          0.04362056, -0.01746167, -0.03075401,  0.03381998,
          0.03152553, -0.03790331,  0.00230766, -0.01792517,
         -0.0345752 , -0.00507946,  0.04930099,  0.00083873],
        [-0.00426328,  0.02396865, -0.00831833, -0.01235731,
         -0.03138181,  0.02421636, -0.03594605, -0.00119774,
          0.0180986 ,  0.010736  ,  0.01356366, -0.01035653,
         -0.00898717, -0.030842  ,  0.01313392, -0.03986161,
          0.04114062, -0.01820686,  0.01204392, -0.04023474],
        [-0.03080596,  0.00914155,  0.01575768, -0.01753191,
         -0.03775833, -0.029837  ,  0.01017511, -0.04055346,
         -0.03071892, -0.04480606,  0.00185348, -0.01901089,
          0.00753295,  0.00439757,  0.03166677,  0.02958698,
          0.03776543,  0.01743821, -0.0433646 , -0.01055668],
        [-0.01878985,  0.01050428,  0.02465273, -0.01828571,
          0.0465552 ,

In [19]:
embedded_words[0]

array([1805, 5986, 7683,    0,    0,    0,    0,    0,    0,    0])

In [21]:
intake = np.expand_dims(embedded_words[0], axis=0)
model.predict(intake)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


array([[[ 0.02378196, -0.03409757, -0.01339421, -0.04283425,
          0.01970315,  0.00146086, -0.03177111, -0.00470096,
          0.04362056, -0.01746167, -0.03075401,  0.03381998,
          0.03152553, -0.03790331,  0.00230766, -0.01792517,
         -0.0345752 , -0.00507946,  0.04930099,  0.00083873],
        [-0.00426328,  0.02396865, -0.00831833, -0.01235731,
         -0.03138181,  0.02421636, -0.03594605, -0.00119774,
          0.0180986 ,  0.010736  ,  0.01356366, -0.01035653,
         -0.00898717, -0.030842  ,  0.01313392, -0.03986161,
          0.04114062, -0.01820686,  0.01204392, -0.04023474],
        [-0.03080596,  0.00914155,  0.01575768, -0.01753191,
         -0.03775833, -0.029837  ,  0.01017511, -0.04055346,
         -0.03071892, -0.04480606,  0.00185348, -0.01901089,
          0.00753295,  0.00439757,  0.03166677,  0.02958698,
          0.03776543,  0.01743821, -0.0433646 , -0.01055668],
        [-0.01878985,  0.01050428,  0.02465273, -0.01828571,
          0.0465552 ,